In [15]:
import numpy as np
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))
x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5
weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])
weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass

## TODO: Calculate output error
error = target - output

In [16]:
hidden_layer_input

array([ 0.24, -0.46])

In [17]:
# TODO: Calculate error term for output layer
# output error term is a scalar, it is the derivative of the error w.r.t. the one output_layer_in 
output_error_term = error * output * (1 - output)
output_error_term 

0.028730669543515018

In [18]:
weights_hidden_output

array([ 0.1, -0.3])

In [19]:
np.dot(output_error_term, weights_hidden_output)

array([ 0.00287307, -0.0086192 ])

In [20]:
output_error_term * weights_hidden_output

array([ 0.00287307, -0.0086192 ])

In [21]:
hidden_layer_output

array([ 0.55971365,  0.38698582])

In [22]:
# TODO: Calculate error term for hidden layer
# output error term is a scalar, weights_hidden_output is a (2,) np.array, 
# * broadcast the scalar to each ele of the np.array
# or we can use np.dot
# hidden_layer_output is a (2,) np.array
# when two np.array of the same shape *, * is performed elementwise
# hidden_error_term has shape (2,), is the derivative of the error w.r.t two hidden layer inputs
hidden_error_term = output_error_term * weights_hidden_output*hidden_layer_output * (1-hidden_layer_output)
# or: hidden_error_term = np.dot(output_error_term, weights_hidden_output) *hidden_layer_output * (1-hidden_layer_output)

In [23]:
hidden_error_term

array([ 0.00070802, -0.00204471])

In [24]:
x[:,None]

array([[ 0.5],
       [ 0.1],
       [-0.2]])

In [25]:
# TODO: Calculate change in weights for hidden layer to output layer
# if we multiply the output_error_term by hidden_layer_output
# we get the derivative of the error w.r.t the weights_hidden_output
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

In [26]:
# if we multiply each ele of the hidden_error_term, the derivative of the error w.r.t the two hidden layer inputs
# by the three inputs, we get the derivative of the error w.r.t weights_input_hidden
delta_w_i_h = learnrate * hidden_error_term * x[:,None]
delta_w_i_h

array([[  1.77005547e-04,  -5.11178506e-04],
       [  3.54011093e-05,  -1.02235701e-04],
       [ -7.08022187e-05,   2.04471402e-04]])

In [27]:
# TODO: Calculate change in weights for input layer to hidden layer
print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

Change in weights for hidden layer to output layer:
[ 0.00804047  0.00555918]
Change in weights for input layer to hidden layer:
[[  1.77005547e-04  -5.11178506e-04]
 [  3.54011093e-05  -1.02235701e-04]
 [ -7.08022187e-05   2.04471402e-04]]
